### ISSUE TITLE
MessageBox abstraction

### ISSUE THREAD

**Issue by pmacn** [Haacked/Rothko#28]
Was going to add some methods on `IDialogFacade` for showing message boxes when I ran in to [CA1300](https://msdn.microsoft.com/en-us/library/ms182191.aspx).

So I thought about only implementing the overload that takes all parameters up to and including `MessageBoxOptions`. Guess another approach would be to implement the ones that take an `IWin32Window` and check the LTR settings on the window. Could even make it take a handle and create an `IWin32Window` internally to simplify use from WPF.

Any preference? Mine would be that people stop using `MessageBox` but I don't see that happening. :-/

**Comment by Haacked** [comment]
Implement the single overload on the interface and people can add the others via extension methods. Or we could. :)

**Comment by pmacn** [comment]
Fixed in #30 I just forgot about links to make this auto-close
