### ISSUE TITLE
File.WriteAllText does not accept encoding.

### ISSUE THREAD

**Issue by grokys** [Haacked/Rothko#49]
The ``IFileFacade.ReadAllText` method accepts an `Encoding` parameter but the `IFileFacade.WriteAllText` does not. Is this intentional or an oversight? It seems to me that specifying the encoding on writing a text file is equally, if not more, important than specifying it on read...

**Comment by Haacked** [comment]
Almost certainly an oversight related to what I specifically needed at the time. PRs welcome!

**Comment by Niladri24dutta** [comment]
@Haacked  Hi Phil, created a PR for this fix https://github.com/Haacked/Rothko/pull/52 
let me know if this can be merged.

**Comment by Haacked** [comment]
Fixed by #52

**Comment by Haacked** [comment]
Fixed by #52
